update buildscript. Revert z3 export changes

diff --git a/buildscript b/buildscript
--- a/buildscript
+++ b/buildscript
@@ -41,11 +41,10 @@ display_help() {
     echo "Options:"
     echo "  -j <num_threads>    Set the number of threads for building (default: 4)"
     echo "  --install DIR     Installation directory (default: pwd)"
+    echo "  --preset <ALL>    SMT configuration. ALL enables all SMTs (default: minimal configuration CUDD-Z3)"
     echo "  --help            Display this help message"
     echo ""
-    echo "crave2uvm installation requires systemc and uvm-systemc libraries. Which can be installed with following scripts:"
-    echo "  ./setup_systemc.sh --install /opt/shared/systemc/CentOS/2.3.4-cxx17"
-    echo "  ./setup_uvm_systemc.sh --install /opt/shared/systemc/CentOS/2.3.4-cxx17"
+    echo "The installation of crave2uvm requires the libraries systemc and uvm-systemc, they are automatically installed by this script if the environment variables SYSTEMC_HOME and UVM_SYSTEMC_HOME are not set."
 }
 
 
@@ -53,6 +52,7 @@ display_help() {
 NUM_THREADS=4  
 CMAKE_INSTALL_PREFIX="$(pwd)"
 LOG_FILE="crave2uvm_build.log"
+PRESET="CUDD-Z3"
 # Truncate the log file before each run
 > "${LOG_FILE}"
 
@@ -69,6 +69,15 @@ while [[ $# -gt 0 ]]; do
                 shift 2
             else
                 echo "Error: Argument for --install is missing." >&2
+                exit 1
+            fi
+            ;;
+        --preset)
+            if [[ -n "$2" ]]; then
+                PRESET="$2"
+                shift 2
+            else
+                echo "Error: Argument for --preset is missing." >&2
                 exit 1
             fi
             ;;
@@ -136,11 +145,10 @@ fi
 
 # Run cmake preset
 log "Running cmake preset..."
-cmake --preset ALL -DCMAKE_INSTALL_PREFIX="$CMAKE_INSTALL_PREFIX" |& tee -a "${LOG_FILE}" || { log "Error: Failed to run cmake preset."; exit 1; }
-pushd build/ALL || { log "Error: Failed to navigate to build directory."; exit 1; }
+cmake --preset $PRESET -DCMAKE_INSTALL_PREFIX="$CMAKE_INSTALL_PREFIX" |& tee -a "${LOG_FILE}" || { log "Error: Failed to run cmake preset."; exit 1; }
+pushd build/${PRESET} || { log "Error: Failed to navigate to build directory."; exit 1; }
 
 log "Building and installing using Ninja..."
 ninja install |& tee -a "${LOG_FILE}" 
 
 popd
-
